### ISSUE TITLE
Rainbow parentheses are gone when syntax highlighting is enabled.

### ISSUE THREAD

**Issue by rightfold** [amdt/vim-niji#36]
I usually work without syntax highlighting, but I turn it on on occasion. However, the coloured parentheses are gone when I do `syntax on`, and they don't come back after `syntax off`.

**Comment by amdt** [comment]
Thanks for reporting this issue, however I don't believe there is a fix for this case.

Niji uses ':highlight' to colour the parentheses, which ':syntax on' is designed to override. You should use ':syntax enable' to maintain any existing highlighting, whilst still loading a syntax file.
